class:
    object:
        instance:
            method:
                params: executables
components:
    ide-extensions:
        vscode: pa-data-team.vsix
    tools:
        exampletool:
            brew:
                source:
                    cask
                args:
                    argstring
                pkg:   
                    id
            winget:
                source:
                    cask
                args:
                    argstring
                pkg:   
                    id
            apt:
                args:
                    argstring
                pkg:   
                    id
            apt-get:
                args:
                    argstring
                pkg:   
                    id
            bash:
                script:
                    scriptname.sh
                args:
                    argstring
            powershell:
                script:
                    scriptname.ps1
                args:
                    argstring
        azurecli:
            brew: formulae;azure-cli
            winget: winget;Microsoft.AzureCLI
        azurestorage:
            brew: cask;microsoft-azure-storage-explorer
            winget: winget;Microsoft.AzureStorageExplorer
        chrome:
            brew: cask;google-chrome
            winget: winget;Google.Chrome
        conda:
            bash: install-conda.sh
        curl:
            apt-get: curl
        dbeaverce:
            brew: cask;dbeaver-community
            winget: winget;dbeaver.dbeaver
        devenv:
            bash: devenv.sh
            powershell: devenv.ps1
        dirstat:
            brew: cask;disk-inventory-x
            winget: winget;WinDirStat.WinDirStat
        docker:
            brew: cask;docker
            winget: winget;Docker.DockerDesktop
        everything:
            brew: cask;easyfind
            winget: winget;voidtools.Everything
        exampletool:
            apt:
                args: argstring
                pkg: id
            apt-get:
                args: argstring
                pkg: id
            bash:
                args: argstring
                script: scriptname.sh
            brew:
                args: argstring
                pkg: id
                source: cask
            powershell:
                args: argstring
                script: scriptname.ps1
            winget:
                args: argstring
                pkg: id
                source: cask
        git:
            brew: formulae;git
            winget: winget;Git.Git
        github:
            brew: cask;github
            winget: winget;GitHub.GitHubDesktop
        googledrive:
            brew: cask;google-drive
            winget: winget;Google.BackupAndSync
        maven:
            apt-get: maven
        miro:
            brew: cask;miro
            winget: winget;Miro.Miro
        notion:
            brew: cask;notion
            winget: winget;Notion.Notion
        office:
            brew: cask;microsoft-office
            winget: winget;Microsoft.officedeploymenttool
        onedrive:
            brew: cask;onedrive
            winget: winget;Microsoft.OneDrive
        openjdk11:
            apt-get: openjdk-11-jdk
        plaintxteditor:
            brew: cask;coteditor
            winget: winget;Notepad++.Notepad++
        postman:
            brew: cask;postman
            winget: winget;Postman.Postman
        python:
            bash: install-python.sh
            winget: winget;Python.Python.3
        sejdapdf:
            brew: cask;sejda-pdf
            winget: winget;Sejda.PDFDesktop
        sevenzip:
            brew: formulae;sevenzip
            winget: winget;7zip.7zip
        ssh:
            winget: winget;PuTTY.PuTTY
        vlc:
            brew: cask;vlc
            winget: winget;VideoLAN.VLC
        vscode:
            brew: cask;visual-studio-code
            winget: winget;Microsoft.VisualStudioCode
        windowmanager:
            brew: cask;bettertouchtool
            winget: winget;Microsoft.PowerToys
        zoom:
            brew: cask;zoom
            winget: winget;Zoom.Zoom
    utilities:
        open-here-shell:
            regedit: open-here.reg
flows:
    business:
    - base
    - qol
    - business
    data:
    - base
    - qol
    - devbase
    - data
    dev:
    - base
    - qol
    - devbase
    - dev
stages:
    base:
        tools:
        - chrome
        - notion
        - googledrive
        - miro
        - python
    business:
        tools:
        - onedrive
        - office
        - zoom
    data:
        devenv:
        - conda
        - python
        ide-extensions:
        - pa-data-team.vsix
        tools:
        - dbeaverce
        - azurestorage
        - conda
    devbase:
        devenv:
        - python
        - conda
        - openjdk11
        - maven
        tools:
        - vscode
        - docker
        - git
        - github
        - ssh
        - azurecli
        - postman
        - devenv
        utilites:
        - open-here-shell
    qol:
        tools:
        - vlc
        - everything
        - windowmanager
        - sevenzip
        - plaintxteditor
        - dirstat
        - sejdapdf

